MBTA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

#url routing here
#another test
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='trip_add'), name='home'),
    path('trips/', include('OnTime.urls')),
    path('admin/', admin.site.urls),
]

OnTime/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.TripListView.as_view(), name = 'trip_changelist'),
    path('add/', views.TripCreateView.as_view(), name = 'trip_add'),
    path('<int:pk>/', views.TripUpdateView.as_view(),name = 'trip_change'),
    path('<int:pk>/load', views.load_trips, name = 'load-trips'),

    path('ajax/load-starting_stops/', views.load_starting_stops, name='ajax_load_starting_stops'),  # <-- this one here
    path('ajax/load-ending_stops/', views.load_ending_stops, name='ajax_load_ending_stops'),

    #path('ajax/load-trips/', views.load_ending_stops, name = 'ajax-load-trips'),
]

OnTime/models.py
from django.db import models
from . import mbta_api

#list of all Commuter Rail Lines
lines_list = mbta_api.create_lines_list("https://api-v3.mbta.com")

#model to represent a lint
class Line(models.Model):
    #list of all MBTA commuter rail lines
    lines_list = mbta_api.create_lines_list("https://api-v3.mbta.com")
    name = models.CharField(max_length = 300, choices=lines_list)

    def __str__(self):
        return self.name

class Starting_Stop(models.Model):
    name = models.CharField(max_length=150)
    line = models.ForeignKey(Line, on_delete=models.CASCADE)
    index = models.IntegerField(default=2)

    def __str__(self):
        return self.name

class Ending_Stop(models.Model):
    name = models.CharField(max_length=150)
    line = models.ForeignKey(Line, on_delete=models.CASCADE)
    index = models.IntegerField(default=2)


    def __str__(self):
        return self.name
    

#model to represent a basic trip on the MBTA
class TripInput(models.Model):
    name = models.CharField(max_length=50, default='New Trip')
    line = models.ForeignKey(Line, on_delete=models.CASCADE)
    starting_stop = models.ForeignKey(Starting_Stop, on_delete=models.CASCADE)
    starting_time = models.TimeField()
    ending_stop = models.ForeignKey(Ending_Stop, on_delete=models.CASCADE)
    ending_time = models.TimeField()

    def __str__(self):
        return ("Trip Name: " + self.name)



def get_Trip_Direction(Starting_Stop, Ending_Stop):
    if (Starting_Stop.index > Ending_Stop.index):
        return 1;
    else:
        return 0;

OnTime/forms.py
from django import forms
from .models import TripInput,Starting_Stop, Ending_Stop

class TripInputForm(forms.ModelForm):
    class Meta:
        model = TripInput
        fields = {'name', 'line', 'starting_stop', 'ending_stop', 'starting_time', 'ending_time'}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['starting_stop'].queryset = Starting_Stop.objects.none()
        self.fields['ending_stop'].queryset  = Ending_Stop.objects.none()

        if 'line' in self.data:
            try:
                line_id = int(self.data.get('line'))
                self.fields['starting_stop'].queryset = Starting_Stop.objects.filter(line_id=line_id).order_by('name')
                self.fields['ending_stop'].queryset = Ending_Stop.objects.filter(line_id=line_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['starting_stop'].queryset = self.instance.line.starting_stop_set.order_by('name')
            self.fields['ending_stop'].queryset = self.instance.line.ending_stop_set.order_by('name')

OnTime/views.py
from django.shortcuts import render
from .models import TripInput, Starting_Stop, Ending_Stop, get_Trip_Direction
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from .forms import TripInputForm
from . import mbta_api
from django.http import HttpResponse

# Create your views here.
class TripListView(ListView):
    print("ran load_stops")
    model = TripInput
    context_object_name = 'trip'

class TripCreateView(CreateView):
    model = TripInput
    #fields = ('line', 'starting_stop', 'starting_time', 'ending_stop', 'ending_time')
    form_class = TripInputForm
    success_url = reverse_lazy('trip-changelist')

class TripUpdateView(UpdateView):
    model = TripInput
    #fields = ('line', 'starting_stop', 'starting_time', 'ending_stop', 'ending_time')
    form_class  = TripInputForm
    success_url = reverse_lazy('trip-changelist')

def load_starting_stops(request):
    print("ran starting stops")

    line_id = request.GET.get('line')
    starting_stops = Starting_Stop.objects.filter(line_id=line_id).order_by('name')
    print(starting_stops)
    return render(request, 'OnTime/starting_stop_dropdown_list.html', {'starting_stops':starting_stops})

def load_ending_stops(request):
    print("ran endinf stops")

    line_id = request.GET.get('line')
    ending_stops = Ending_Stop.objects.filter(line_id=line_id).order_by('name')
    print(ending_stops)
    return render(request, 'OnTime/ending_stop_dropdown_list.html', {'ending_stops':ending_stops}) 

def load_trips(request, pk):
    base_url = "https://api-v3.mbta.com"

    current_input = TripInput.objects.get(pk = pk)
    line = current_input.line
    starting_stop_id = current_input.starting_stop.index
    starting_stop = current_input.starting_stop.name
    ending_stop_id = current_input.ending_stop.index
    ending_stop = current_input.ending_stop.name
    begin_time = current_input.starting_time

    travel_direction = mbta_api.find_travel_direction(starting_stop_id, ending_stop_id)

    trips = mbta_api.find_trips(base_url, travel_direction, begin_time, 'CR-Franklin', starting_stop)
    times = mbta_api.find_times(base_url, trips, starting_stop, ending_stop)
    #return HttpResponse(mbta_api.create_lines_list("https://api-v3.mbta.com")
    return HttpResponse((trips))

    

OnTime/templates/OnTime/ending_stop_dropdown_list.html
<option value="">---------</option>
{% for ending_stop in ending_stops %}
<option value="{{ ending_stop.pk }}">{{ ending_stop.name }}</option>
{% endfor %}

OnTime/templates/OnTime/starting_stop_dropdown_list.html
<option value="">---------</option>
{% for starting_stop in starting_stops %}
<option value="{{ starting_stop.pk }}">{{ starting_stop.name }}</option>

{% endfor %}

OnTime/templates/OnTime/stop_dropdown_list.html
<option value="">---------</option>
{% for starting_stop in starting_stops %}
<option value="{{ starting_stop.pk }}">{{ starting_stop.name }}</option>
{% endfor %}

OnTime/templates/OnTime/trip_form.html
{% extends 'base.html'%}
{% block content %}
  <h2>Person Form</h2>
  <form method="post" id = "tripForm" data-ending-stops-url = "{% url 'ajax_load_ending_stops' %}" data-starting-stops-url = "{% url 'ajax_load_starting_stops' %}"novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'trip_changelist' %}">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    console.log("Ajax worked");
    $("#id_line").change(function () {
      var url = $("#tripForm").attr("data-starting-stops-url");  // get the url of the `load_cities` view
      var lineId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'line': lineId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
        $("#id_starting_stop").html(data);  // replace the contents of the city input with the data that came from the server
        console.log(data);
        }
      });

    });
  </script>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  console.log("Ajax worked");
  $("#id_line").change(function () {
    var url = $("#tripForm").attr("data-ending-stops-url");  // get the url of the `load_cities` view
    var lineId = $(this).val();  // get the selected country ID from the HTML input

    $.ajax({                       // initialize an AJAX request
      url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
      data: {
        'line': lineId       // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
      $("#id_ending_stop").html(data);  // replace the contents of the city input with the data that came from the server
      console.log(data);
      }
    });

  });
</script>
{% endblock %}

OnTime/templates/OnTime/trip_list.html
<!doctype html>
<html lang="en-us">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="utf-8">
    <title>Trip List</title>
    </head>

   <body>
       <div class= "container">
            <div class = "jumbotron" s>
                <h1>Trip List</h1>
                {% for trip in trip data %}
            </div>
       </div> 
       

   </body>

OnTime/templates/OnTime/tripinput_form.html
{% extends 'base.html'%}
{% block content %}
<div style = "padding-top: 0px;;">
  <div class = "jumbotron" style = "padding: 0px;">
    <h2 class = "text-center" style= "font-size: 80px; padding-top: 0px; background-color: white;">Enter Trip Data</h2>
  </div>
  
<button type="button" class="btn btn-primary btn-lg">Large button</button>

</div>
<div class = "text-center">
      <h2>Enter Trip Data</h2>
      <form style = "text-align: center; display: block;"post" id = "tripForm" data-ending-stops-url = "{% url 'ajax_load_ending_stops' %}" data-starting-stops-url = "{% url 'ajax_load_starting_stops' %}"novalidate>
        <table style = "margin-left: auto; margin-right: auto;">
          {{ form.as_table }}
        </table>
        <button type="submit" id = "submitButton">Save</button>
        <a href="{% url 'trip_changelist' %}">Nevermind</a>
      </form>
</div>
  <span id = "trip_span">
  </span>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    console.log("Ajax worked");
    $("#id_line").change(function () {
      var url = $("#tripForm").attr("data-starting-stops-url");  // get the url of the `load_cities` view
      var lineId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'line': lineId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
        $("#id_starting_stop").html(data);  // replace the contents of the city input with the data that came from the server
        console.log(data);
        }
      });

    });
  </script>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  console.log("Ajax worked");
  $("#id_line").change(function () {
    var url = $("#tripForm").attr("data-ending-stops-url");  // get the url of the `load_cities` view
    var lineId = $(this).val();  // get the selected country ID from the HTML input
    console.log(lineId);

    $.ajax({                       // initialize an AJAX request
      url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
      data: {
        'line': lineId       // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
      $("#id_ending_stop").html(data);  // replace the contents of the city input with the data that came from the server
      console.log(data);
      }
    });

  });
</script>

<!--
<script>src="https://code.jquery.com/jquery-3.3.1.min.js"</script>
<script>
  $("#submitButton").click(function() {
    console.log("#button click working");
    var url = $("#submitButton").attr("data-create-list");
    var lineId = $("#id_line").val();
    var starting_stop = $("#id_starting_stop").val();
    var ending_stop = $("#id_ending_stop").val();
    var starting_time = $("#id_starting_time").val();
    var ending_time = $("#id_ending_time").val();
    console.log(ending_stop);

    $.ajax ({
      url: url,
      data: {
        'line': lineId,
        'starting_stop': starting_stop,
        'ending_stop': ending_stop,
        'starting_time': starting_time,
        'ending_time':ending_time,
        },
      success: function (data) {
        //$("#trip_span").html(data);
      }
    });
  });
</script> -->

{% endblock %}

OnTime/templates/OnTime/tripinput_list.html
{% extends 'base.html'%}


{% block title %}Create Trip Module{% endblock %}

{% block content %}

  <p>
    <a href="{% url 'trip_add' %}">Add Trip</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Line</th>
        <th>Starting Stop</th>
        <th>Starting Time</th>
        <!--<th>Ending Stop</th> -->
        <th>Ending Time</th>
      </tr>
    </thead>
    <tbody>
      {% for trip in trip %}
        <tr>
          <td><a href="{% url 'trip_change' trip.pk %}">{{ trip.line.name }}</a></td>
          <td>{{ trip.starting_stop.name }}</td>
          <td>{{ trip.starting_time.name }}</td>
          <!--<td>{{ trip.ending_stop.name }}</td> -->
          <td>{{trip.ending_time.name}}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No Trip in the database. <a href="{% url 'trip_add' %}">Add the first Trip</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="utf-8">
    <title>{% block title %}Create Trip{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  </head>
  <body>
    <div style ="background-color: purple; color: aliceblue;">
      <h1 class = "text-center" style = "padding-top: 10px; padding-bottom: 10px; font-size: 100px;">MBTA OnTime</h1>
    </div>
    
    
    {% block content %}
    {% endblock %}
  </body>
</html>